### PR TITLE
Replace Travis CI with GitHub Actions

### LINKED ISSUE #3: Replace Travis CI with GitHub actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #3.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
If you push `ci.yml` to `master` I can rebase and we can see the tests unfold before the merge. It might be safer.

**Review by g-andrade — CHANGES_REQUESTED** [review]
Much obliged.

I kindly ask for analogous changes as requested in [aequitas PR #5](https://github.com/g-andrade/aequitas/pull/5).

(I'm linking to those changes rather than repeating the same comments on the same places and potentially get the same answers a thousand fold, and therefore make myself feel less moronic about the whole process.)

**Comment by paulo-ferraz-oliveira** [comment]
620d21d + c1edae8

**Comment by g-andrade** [comment]
Thanks a lot :+1:

**Pull request merged**
